dist: bionic
sudo: false
language: cpp
compiler: gcc

before_install:
        - pip install --user cpp-coveralls
        - travis_retry curl -L https://www.libsdl.org/release/SDL2-2.0.12.tar.gz | tar xz
        - cd SDL2-2.0.12
        - ./configure
        - make
        - sudo make install
        - cd -
        - travis_retry curl -L https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.5.tar.gz | tar xz
        - cd SDL2_image-2.0.5
        - ./configure
        - make
        - sudo make install
        - cd -
        - travis_retry curl -L https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.15.tar.gz | tar xz
        - cd SDL2_ttf-2.0.15
        - ./configure
        - make
        - sudo make install
        - cd -
        - travis_retry curl -L https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.4.tar.gz | tar xz
        - cd SDL2_mixer-2.0.4
        - ./configure
        - make
        - sudo make install
        - cd -

script:
        - CXX=/usr/bin/g++-7 CC=/usr/bin/gcc-7
        - cmake -DCOVERAGE=1 .
        - cmake --build . 
        - ./test/test_gbe

after_success:
        - coveralls --root . -E ".*gtest.*" -E ".*CMakeFiles.*"
