dist: bionic
sudo: false
language: cpp
compiler: gcc

before_install:
        - pip install --user cpp-coveralls

script:
        - CXX=/usr/bin/g++-7 CC=/usr/bin/gcc-7
        - cmake -DCOVERAGE=1 .
        - cmake --build . 
        - ./test/test_gbe

after_success:
        - coveralls --root . -E ".*gtest.*" -E ".*CMakeFiles.*"
